# **Library & Drive**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
pip install tensorflow.io

     |████████████████████████████████| 23.1 MB 1.5 MB/s 


In [ ]:
from IPython.display import Audio

import tensorflow as tf
import tensorflow_io as tfio
import matplotlib.pyplot as plt
import numpy as np
import glob

In [ ]:
#pip install python_speech_features

In [ ]:
import os
import librosa
import pickle
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from tqdm import tqdm
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from keras.layers import Conv2D, MaxPool2D, Flatten, Dense, Dropout
from keras.models import Sequential
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
#from python_speech_features import mfcc

# **Load Data Gumaman**

In [ ]:
daftar_gdangdut = glob.glob('/content/drive/MyDrive/Dataset01/Dangdut/Gumam/*')
daftar_gkpop = glob.glob('/content/drive/MyDrive/Dataset01/KPop/Gumam/*')

In [ ]:
#baca file dan masukin ke list
gumaman_dangdut =[]
for i in range(len(daftar_gdangdut)):
  gumam = tf.io.read_file(daftar_gdangdut[i])
  suara = tfio.audio.decode_mp3(gumam)
  gumaman_dangdut.append(suara)


gumaman_kpop =[]
for i in range(len(daftar_gkpop)):
  gumam = tf.io.read_file(daftar_gkpop[i])
  suara = tfio.audio.decode_mp3(gumam)
  gumaman_kpop.append(suara)

In [ ]:
gumaman_kpop

[<tf.Tensor: shape=(9231360, 1), dtype=float32, numpy=
 array([[ 0.0000000e+00],
        [ 0.0000000e+00],
        [ 0.0000000e+00],
        ...,
        [-5.4995853e-05],
        [ 6.2783435e-04],
        [ 6.1394507e-04]], dtype=float32)>,
 <tf.Tensor: shape=(8942296, 1), dtype=float32, numpy=
 array([[-1.0203528e-05],
        [-1.5740072e-05],
        [-1.7388518e-05],
        ...,
        [ 3.9938779e-05],
        [ 6.0729850e-05],
        [ 5.0359940e-05]], dtype=float32)>,
 <tf.Tensor: shape=(8942296, 1), dtype=float32, numpy=
 array([[-1.0203528e-05],
        [-1.5740072e-05],
        [-1.7388518e-05],
        ...,
        [ 3.9938779e-05],
        [ 6.0729850e-05],
        [ 5.0359940e-05]], dtype=float32)>,
 <tf.Tensor: shape=(9245656, 1), dtype=float32, numpy=
 array([[-4.4457088e-06],
        [-8.1725630e-06],
        [-7.7637205e-06],
        ...,
        [ 1.8270534e-03],
        [ 2.3665898e-03],
        [ 1.8961872e-03]], dtype=float32)>,
 <tf.Tensor: shape=(11251096, 1)

In [ ]:
#train
x=[]
y=[]

#mencacah/motong lagu
for j in range(len(daftar_gdangdut)):
  for i in range(0, len(gumaman_dangdut[j])-44100, 11025):
    x.append(gumaman_dangdut[j][i:i+44100])
    y.append(0)

for j in range(len(daftar_gkpop)):
  for i in range(0, len(gumaman_kpop[j])-44100, 11025):
    x.append(gumaman_kpop[j][i:i+44100])
    y.append(1)

'\nfor j in range(len(daftar_gjpop)):\n  for i in range(0, len(gumaman_jpop[j])-44100, 11025):\n    x.append(gumaman_jpop[j][i:i+44100])\n    y.append(2)\n\nfor j in range(len(daftar_gpop)):\n  for i in range(0, len(gumaman_pop[j])-44100, 11025):\n    x.append(gumaman_pop[j][i:i+44100])\n    y.append(3)\n'

In [ ]:
x = np.asarray(x)
y = np.asarray(y)

In [ ]:
y
#y.shape

array([0, 0, 0, ..., 1, 1, 1])

In [ ]:
label_encoder = LabelEncoder()
label_encoded = label_encoder.fit_transform(y)

In [ ]:
label_encoded

array([0, 0, 0, ..., 1, 1, 1])

In [ ]:
label_encoded=label_encoded[:,np.newaxis]

In [ ]:
label_encoded

array([[0],
       [0],
       [0],
       ...,
       [1],
       [1],
       [1]])

In [ ]:
one_hot_encoder = OneHotEncoder(sparse=False)
one_hot_encoded = one_hot_encoder.fit_transform(label_encoded)

In [ ]:
one_hot_encoded

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [ ]:
y = one_hot_encoded

In [ ]:
maks = np.max(x)
mins = np.min(x)

#normalisasi
x = (x-mins)/(maks-mins)
#y = (y-mins)/(maks-mins)

In [ ]:
x

array([[[0.5660316 ],
        [0.5660273 ],
        [0.56602603],
        ...,
        [0.5660046 ],
        [0.56586987],
        [0.56586444]],

       [[0.5619971 ],
        [0.56287265],
        [0.5639755 ],
        ...,
        [0.5665793 ],
        [0.5665167 ],
        [0.5664939 ]],

       [[0.5697608 ],
        [0.56930095],
        [0.56876004],
        ...,
        [0.5660639 ],
        [0.566091  ],
        [0.5661264 ]],

       ...,

       [[0.5661747 ],
        [0.5656962 ],
        [0.56544554],
        ...,
        [0.5659916 ],
        [0.56598556],
        [0.56599766]],

       [[0.56604743],
        [0.5660389 ],
        [0.56604606],
        ...,
        [0.56604743],
        [0.5660431 ],
        [0.56603867]],

       [[0.56609505],
        [0.5658925 ],
        [0.5657439 ],
        ...,
        [0.566036  ],
        [0.56605107],
        [0.5660517 ]]], dtype=float32)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [ ]:
print(x.shape)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(8955, 44100, 1)
(7164, 44100, 1)
(7164, 2)
(1791, 44100, 1)
(1791, 2)


# **Model**

In [ ]:
# CNN 1D
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Activation

#size_ = 8 #inputnya ada 8, dr pclass-embarked

model = Sequential()

model.add(Conv1D(128, kernel_size=3, input_shape = (x.shape[1],1), activation = 'relu'))
model.add(Flatten())

model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(64, activation='relu'))

#model.add(Dense(units = 8, activation = 'relu'))
model.add(Dense(units = 2, activation = 'softmax'))

model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics=['accuracy'])

In [ ]:
model.fit(x_train,y_train, batch_size=20, epochs=50)

Epoch 1/50
359/359 [==============================] - 56s 128ms/step - loss: 1.0325 - accuracy: 0.5099
Epoch 2/50
  6/359 [..............................] - ETA: 44s - loss: 0.6990 - accuracy: 0.5167

KeyboardInterrupt: ignored

In [ ]:
#model.save_weights('f1_classifiergumam.h5')
#read file
model.load_weights('/content/drive/MyDrive/Dataset01/f1_classifiergumam.h5')

In [ ]:
lur = model.predict(x_test)

In [ ]:
lur

array([[3.7499070e-16, 1.0000000e+00],
       [7.4571616e-29, 1.0000000e+00],
       [8.1414337e-29, 1.0000000e+00],
       ...,
       [4.9899347e-28, 1.0000000e+00],
       [2.0520323e-29, 1.0000000e+00],
       [8.5616235e-29, 1.0000000e+00]], dtype=float32)

In [ ]:
lur[50]

array([5.0949437e-18, 1.0000000e+00], dtype=float32)

In [ ]:
predictions = np.argmax(lur, axis=1)
y_test = one_hot_encoder.inverse_transform(y_test)

In [ ]:
predictions

array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
predict = pd.DataFrame(predictions)

In [ ]:
predict

0
0     1
1     1
2     1
3     1
4     1
...  ..
1786  1
1787  1
1788  1
1789  1
1790  1

[1791 rows x 1 columns]

In [ ]:
predict[(predict[0]==1)].shape

(1791, 1)

In [ ]:
print(predictions)

[1 1 1 ... 1 1 1]


In [ ]:
y_test

array([[1],
       [1],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [ ]:
accuracy_score(predictions, y_test)

0.4796203238414294

# **Predict with new file**

In [ ]:
ftest = '/content/drive/MyDrive/Dataset01/KPop/Gumam/Akdong Musician - Give Love.mp3'

In [ ]:
ftest

'/content/drive/MyDrive/Dataset01/KPop/Gumam/Akdong Musician - Give Love.mp3'

In [ ]:
f_Test = tf.io.read_file(ftest)
s_Test = tfio.audio.decode_mp3(f_Test)

In [ ]:
s_Test

<tf.Tensor: shape=(8942296, 1), dtype=float32, numpy=
array([[-1.0203528e-05],
       [-1.5740072e-05],
       [-1.7388518e-05],
       ...,
       [ 3.9938779e-05],
       [ 6.0729850e-05],
       [ 5.0359940e-05]], dtype=float32)>

In [ ]:
input = []
for i in range(0, len(s_Test)-44100, 11025):
    input.append(s_Test[i:i+44100])

input = np.asarray(input)
maks = np.max(input)
min = np.min(input)

input = (input-min)/(maks-min)

In [ ]:
input.shape

(808, 44100, 1)

In [ ]:
hasil = model.predict(input)
hasil = np.argmax(hasil,axis=1)

In [ ]:
hasil

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,

In [ ]:
hasil = pd.DataFrame(hasil)
jmlh_0 = hasil[(hasil[0]==0)].shape[0]
jmlh_1 = hasil[(hasil[0]==1)].shape[0]


if jmlh_0 > jmlh_1 :
  print('dangdut')
elif jmlh_0 < jmlh_1 :
  print('kpop')
else :
  print('not known')

kpop
